import { FunctionSquare } from 'lucide-react';
import React from 'react';

export default function SAWMethodology() {
  return (
    <div className="md:col-span-12 glass-card p-6 md:p-8 rounded-xl">
      <div className="flex flex-col lg:flex-row gap-12 items-stretch">
        <div className="lg:w-1/2">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 bg-emerald-400/20 rounded-xl flex items-center justify-center border border-emerald-400/30">
              <FunctionSquare className="text-emerald-400 w-6 h-6" />
            </div>
            <h2 className="text-2xl text-white font-bold">SAW Methodology</h2>
          </div>
          <p className="text-slate-400 mb-8 leading-relaxed font-body">
            Simple Additive Weighting (SAW) is the gold standard for Multi-Criteria Decision Making (MCDM). Preference scores are generated by the precise summation of normalized attribute values weighted by expert-defined priority factors.
          </p>
          <div className="bg-black/40 backdrop-blur-md rounded-2xl p-10 text-center border border-emerald-400/20 shadow-inner">
            <div className="text-emerald-400 tracking-[0.2em] text-3xl md:text-4xl mb-3 font-heading">V<sub>i</sub> = ∑ (w<sub>j</sub> × r<sub>ij</sub>)</div>
            <div className="text-slate-500 uppercase tracking-[0.3em] text-[10px] font-bold">Generalized SAW Formula</div>
          </div>
        </div>
        
        <div className="lg:w-1/2 grid grid-cols-1 sm:grid-cols-2 gap-4 h-full w-full">
          {[
            { step: "01", title: "Normalization", desc: "Converting diverse units (liters, dollars, pH) into a unified 0-1 scale." },
            { step: "02", title: "Weight Assignment", desc: "Experts assign relative importance to each agricultural factor." },
            { step: "03", title: "Aggregation", desc: "Summing products of weights and scores to find the optimal crop." },
            { step: "04", title: "Final Ranking", desc: "Ordering alternatives from most to least suitable for the plot." }
          ].map((s, i) => (
            <div key={i} className="p-5 glass-card rounded-xl border border-white/5 flex flex-col justify-center">
              <div className="text-emerald-400 font-black text-2xl mb-2 opacity-50">{s.step}</div>
              <h4 className="text-white mb-2 font-heading font-bold">{s.title}</h4>
              <p className="text-xs text-slate-500 leading-relaxed">{s.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
