/**
 * FAQ Content — Agri-SAW Pro Chatbot
 * Source: SPK.md, dasar knowledge base.md
 * 5 Kategori, 21 Pertanyaan
 */

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
}

export interface FaqSection {
  id: string;
  title: string;
  items: FaqItem[];
}

export const FAQ_CONTENT: FaqSection[] = [
  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 1: Tentang Sistem — 4 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_sistem',
    title: 'Tentang Sistem',
    items: [
      {
        id: 'faq_sistem_apa',
        question: 'Apa itu Agri-SAW Pro?',
        answer: [
          'Agri-SAW Pro adalah aplikasi sederhana untuk membantu Anda memilih tanaman terbaik. Tanaman yang cocok dengan lahan Anda DAN menguntungkan secara ekonomi.',
          '',
          'Cara kerjanya menggunakan 2 tahap perhitungan:',
          '',
          'TAHAP 1 — Kesesuaian Lahan',
          'Disini sistem menyaring tanaman yang bisa hidup di lahan Anda. Yang dicek: pH tanah, tekstur tanah, ketinggian, sinar matahari, dan curah hujan.',
          '',
          'TAHAP 2 — Analisis Keuntungan',
          'Tanaman yang lolos tahap 1 lalu dihitung keuntungannya. Yang dilihat: biaya tanam, harga jual, berapa banyak hasil panen, seberapa besar risikonya, dan seberapa laku di pasaran.',
          '',
          'Hasil akhirnya adalah daftar tanaman terbaik untuk lahan Anda. Bukan cuma cocok — tapi juga mengantungkan untuk ditanam.',
        ].join('\n'),
      },
      {
        id: 'faq_sistem_komoditas',
        question: 'Tanaman apa saja yang bisa dianalisis?',
        answer: [
          'Saat ini Agri-SAW Pro bisa menganalisis 6 tanaman yang paling umum ditanam di Indonesia:',
          '',
          '• 🌾 Padi — Tanaman pangan pokok. Cocok di dataran rendah sampai sedang. Butuh banyak air.',
          '• 🌽 Jagung — Tanaman serbaguna. Tumbuh di berbagai ketinggian. Tahan kering.',
          '• 🫘 Kedelai — Bisa menyuburkan tanah. Cocok di dataran rendah-sedang. Butuh air sedang.',
          '• 🌶️ Cabai Merah — Sayuran mahal. Cocok di dataran rendah-tinggi. Butuh cukup sinar matahari.',
          '• 🧅 Bawang Merah — Sayuran laku keras. Cocok di dataran rendah-sedang. Butuh sinar matahari penuh.',
          '• 🧄 Bawang Putih — Sayuran dataran tinggi. Cocok di pegunungan. Butuh sinar matahari penuh.',
          '',
          'Keenam tanaman ini dipilih karena kebutuhan lahannya berbeda-beda. Jadi sistem bisa kasih perbandingan yang jelas untuk lahan Anda.',
        ].join('\n'),
      },
      {
        id: 'faq_sistem_cara',
        question: 'Bagaimana cara kerja sistem?',
        answer: [
          'Sistem ini bekerja dalam 2 tahap berurutan. Sederhana saja, seperti menyaring — dari banyak pilihan, diambil yang terbaik.',
          '',
          'TAHAP 1 — Kesesuaian Lahan',
          'Anda akan ditanya soal kondisi lahan: keasaman tanah, tekstur tanah, ketinggian, sinar matahari, dan curah hujan. Jawab saja dengan bahasa sehari-hari — tidak perlu angka teknis.',
          '',
          'Sistem lalu mencocokkan jawaban Anda dengan kebutuhan setiap tanaman. Kalau satu saja kondisi tidak cocok, tanaman itu langsung dikeluarkan. Misalnya lahan Anda di dataran rendah, maka Bawang Putih (butuh dataran tinggi) langsung hilang dari daftar.',
          '',
          'TAHAP 2 — Perhitungan Keuntungan',
          'Tanaman yang lolos Tahap 1 lalu dihitung keuntungannya. Yang dilihat: biaya tanam, harga jual, hasil panen, risiko gagal, dan permintaan pasar.',
          '',
          'Anda bisa pilih prioritas — misalnya "modal terbatas" atau "takut rugi". Sistem akan menyesuaikan perhitungannya.',
          '',
          'HASIL AKHIR',
          'Sistem menampilkan ranking tanaman dari yang paling cocok dan menguntungkan untuk lahan Anda. Lengkap dengan penjelasan singkatnya.',
        ].join('\n'),
      },
      {
        id: 'faq_sistem_filter',
        question: 'Apa perbedaan Tahap 1 dan Tahap 2?',
        answer: [
          'Kedua tahap ini berbeda fungsi, tapi saling melengkapi. Ibu rumah tangga pasti paham: Tahap 1 itu seperti memilih bahan yang masak, Tahap 2 itu memilih mana yang paling enak.',
          '',
          'TAHAP 1 — Kesesuaian Lahan',
          'Tujuan: Memastikan tanaman bisa hidup di lahan Anda.',
          '',
          'Cara kerja: Setiap kondisi lahan dicek satu per satu. Kalau satu saja tidak cocok, tanaman langsung dikeluarkan. Ini batas mutlak — tidak bisa ditawar.',
          '',
          'Yang dicek:',
          '• Keasaman tanah (pH)',
          '• Tekstur tanah (liat, lempung, berpasir)',
          '• ketinggian lahan',
          '• Sinar matahari per hari',
          '• Curah hujan',
          '',
          'TAHAP 2 — Perhitungan Keuntungan',
          'Tujuan: Dari tanaman yang bisa hidup, mana yang paling menguntungkan?',
          '',
          'Cara kerja: Semua faktor ekonomi dihitung bersama. Anda bisa tentukan mana yang lebih penting — misalnya biaya murah atau risiko rendah.',
          '',
          'Yang dicek:',
          '• Biaya produksi (modal tanam per hektar)',
          '• Harga jual (harga pasar rata-rata)',
          '• Hasil panen (berapa ton per hektar)',
          '• Risiko gagal panen',
          '• Permintaan pasar',
          '',
          'Jadi: Tahap 1 = "Bisa hidup nggak?" Tahap 2 = "Kalau bisa hidup, untungnya berapa?"',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 2: Tentang Komoditas — 3 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_komoditas',
    title: 'Tentang Komoditas',
    items: [
      {
        id: 'faq_komoditas_daftar',
        question: 'Tanaman apa saja yang bisa dianalisis?',
        answer: [
          'Saat ini Agri-SAW Pro mendukung 6 tanaman pangan dan sayuran utama di Indonesia:',
          '',
          '• 🌾 Padi — Tanaman pangan pokok. Permintaan pasar paling tinggi. Biaya sekitar Rp 7,2 juta per hektar, hasil rata-rata 5,28 ton per hektar.',
          '• 🌽 Jagung — Tanaman serbaguna. Biaya produksi rendah (Rp 6,2 juta/ha), hasil 5,57 ton/ha.',
          '• 🫘 Kedelai — Bisa menyuburkan tanah. Biaya produksi paling rendah (Rp 5,4 juta/ha), harga jual cukup tinggi (Rp 16.459/kg).',
          '• 🌶️ Cabai Merah — Harga jual paling tinggi (Rp 52.001/kg). Tapi biaya tanamnya juga tinggi (Rp 48,5 juta/ha).',
          '• 🧅 Bawang Merah — Hasil panen paling tinggi (10,05 ton/ha) dan permintaan sangat tinggi.',
          '• 🧄 Bawang Putih — Butuh dataran tinggi. Biaya tanam paling mahal (Rp 91,6 juta/ha), tapi harga jual dan permintaan juga tinggi.',
          '',
          'Masing-masing tanaman punya kebutuhan lahan yang berbeda. Tidak semua tanaman cocok untuk setiap lahan — itu sebabnya kita butuh sistem ini.',
        ].join('\n'),
      },
      {
        id: 'faq_komoditas_mengapa',
        question: 'Mengapa hanya 6 tanaman?',
        answer: [
          'Alasan pemilihan 6 tanaman ini sengaja agar rekomendasi yang diberikan benar-benar akurat:',
          '',
          '• Padi, jagung, kedelai — Ini tanaman pangan utama penyumbang ketahanan pangan nasional.',
          '• Cabai merah, bawang merah, bawang putih — Sayuran dengan harga jual dan permintaan pasar yang besar.',
          '',
          'Keenam tanaman ini juga punya kebutuhan lahan yang sangat berbeda. Ada yang cocok di dataran rendah, ada yang butuh pegunungan. Ada yang butuh banyak air, ada yang tahan kering.',
          '',
          'Perbedaan inilah yang membuat perbandingan jadi bermakna. Kalau semua tanaman butuh kondisi yang sama, tidak perlu sistem untuk memilih.',
          '',
          'Selain itu, data untuk 6 tanaman ini tersedia lengkap dari sumber resmi (BPS, Kementerian Pertanian). Data yang lengkap berarti perhitungan yang lebih akurat.',
        ].join('\n'),
      },
      {
        id: 'faq_komoditas_tidakada',
        question: 'Bagaimana jika tanaman saya tidak ada di daftar?',
        answer: [
          'Kami paham, tidak semua tanaman favorit Anda ada di daftar. Ini yang perlu Anda tahu:',
          '',
          'KENAPA TIDAK BISA TAMBAH TANAMAN SEMBARANG',
          'Setiap tanaman butuh data lengkap — kebutuhan lahan, biaya tanam, harga jual, hasil panen, dan risiko. Tanpa data ini, rekomendasi tidak akan akurat.',
          '',
          'YANG BISA ANDA LAKUKAN',
          '• Gunakan sistem untuk melihat dari 6 tanaman yang ada, mana yang paling cocok dengan lahan Anda.',
          '• Konsultasikan dengan penyuluh pertanian atau Dinas Pertanian setempat untuk tanaman di luar daftar.',
          '',
          'KE DEPAN',
          'Pengembangan selanjutnya bisa menambahkan lebih banyak tanaman. Semakin banyak data yang tersedia, semakin berguna sistem ini untuk petani.',
          '',
          'Yang penting: meskipun tanaman Anda tidak ada di daftar, sistem tetap bisa membantu memilih tanaman terbaik dari yang tersedia untuk kondisi lahan Anda.',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 3: Tentang Kondisi Lingkungan — 4 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_lingkungan',
    title: 'Tentang Kondisi Lingkungan',
    items: [
      {
        id: 'faq_lingkungan_ph',
        question: 'Bagaimana cara mengetahui keasaman tanah?',
        answer: [
          'Keasaman tanah (pH) itu ukuran tanah Anda termasuk asam, netral, atau basa. pH 7 = netral. Di bawah 7 = asam. Di atas 7 = basa.',
          '',
          'Kenapa ini penting? Karena setiap tanaman punya selera pH sendiri. Padi suka tanah agak asam (pH 5,5-6,5), sementara Bawang Putih lebih suka netral (pH 6,0-7,0). Kalau pH tidak cocok, tanaman tidak bisa serap nutrisi dengan baik.',
          '',
          'CARA MEMPERKIRAKAN TANPA ALAT',
          '• Tanaman sering menguning dan kerdil meskipun sudah dipupuk → kemungkinan tanah terlalu asam.',
          '• Tanaman tumbuh hijau dan subur → kemungkinan tanah netral.',
          '',
          'CARA MENGUKUR LEBIH AKURAT',
          '• Beli alat ukur pH atau kertas lakmus di toko pertanian (murah kok).',
          '• Ambil tanah dari kedalaman 15-20 cm, keringkan, larutkan dalam air.',
          '• Ukur larutannya dengan alat.',
          '',
          'KALAU TANAH TERLALU ASAM: Beri kapur pertanian atau dolomit.',
          'KALAU TERLALU BASA: Tambah kompos atau pupuk kandang.',
        ].join('\n'),
      },
      {
        id: 'faq_lingkungan_tekstur',
        question: 'Bagaimana cara mengetahui tekstur tanah?',
        answer: [
          'Tekstur tanah itu tentang apa yang menyusun tanah Anda: pasir, debu, atau lempung. Ini penting karena tekstur menentukan seberapa baik tanah menahan air dan nutrisi.',
          '',
          'Kenapa ini berpengaruh? Tanah yang terlalu berpasir = air cepat habis. Tanah yang terlalu liat = air menggenang. Keduanya tidak ideal untuk semua tanaman.',
          '',
          'CARA MENGETAHUI — AMBIL TANAH BASAH, REMAS:',
          '',
          'TERASA SANGAT LENGKET, SULIT LEPAS',
          '→ Tanah liat. Menahan air dengan baik. Cocok untuk Padi. Tapi keras saat kering.',
          '',
          'TERASA KASAR SEPERTI PASIR, MUDAH HANCUR',
          '→ Tanah berpasir. Air cepat kering, tapi drainase bagus. Cocok untuk Bawang.',
          '',
          'TERASA SEDIKIT LENGKET, BISA DIBENTUK',
          '→ Tanah lempung. Keseimbangan antara drainase dan retensi air. Paling serbaguna. Cocok untuk Jagung dan Kedelai.',
        ].join('\n'),
      },
      {
        id: 'faq_lingkungan_hujan',
        question: 'Bagaimana cara memperkirakan curah hujan?',
        answer: [
          'Curah hujan = seberapa banyak air hujan yang turun di wilayah Anda. Ini penting karena setiap tanaman punya kebutuhan air yang berbeda.',
          '',
          'CARA MEMPERKIRAKAN TANPA ALAT UKUR',
          '• Hampir tiap hari hujan → Curah hujan TINGGI',
          '• Sering hujan, beberapa kali seminggu → Curah hujan SEDANG',
          '• Jarang hujan, hanya sesekali → Curah hujan RENDAH',
          '',
          'CARA MENGUKUR LEBIH AKURAT',
          '• Siapkan wadah silinder (bisa kaleng cat yang bersih). Taruh di area terbuka.',
          '• Setelah hujan, ukur tinggi air dengan penggaris (dalam milimeter).',
          '• Lakukan setiap hari selama minimal 1 bulan untuk dapat gambaran yang akurat.',
          '',
          'KEBUTUHAN AIR MASING-MASING TANAMAN',
          '• Padi: Butuh banyak air — cocok untuk daerah sering hujan.',
          '• Jagung: Sedang — cukup dengan hujan biasa.',
          '• Kedelai: Sedang — tidak terlalu banyak, tidak terlalu sedikit.',
          '• Cabai Merah: Sedang — butuh air teratur tapi tidak tergenang.',
          '• Bawang Merah: Rendah — lebih suka tanah agak kering.',
          '• Bawang Putih: Rendah — tanah yang terlalu basah malah merusak umbinya.',
        ].join('\n'),
      },
      {
        id: 'faq_lingkungan_cahaya',
        question: 'Bagaimana cara memperkirakan sinar matahari?',
        answer: [
          'Yang dimaksud sinar matahari di sini adalah berapa jam lahan Anda dapat sinar matahari langsung setiap harinya. Penting karena sinar matahari adalah "makanan" tanaman.',
          '',
          'CARA MEMPERKIRAKAN',
          'Hitung saja berapa jam lahan Anda kena sinar matahari tanpa terhalang pohon besar, bangunan, atau atap.',
          '',
          'COCOK UNTUK PADI DAN JAGUNG',
          '6-8 jam sinar matahari per hari sudah cukup.',
          '',
          'COCOK UNTUK KEDELAI DAN CABAI MERAH',
          'Butuh 8-10 jam sinar matahari per hari.',
          '',
          'COCOK UNTUK BAWANG MERAH DAN BAWANG PUTIH',
          'Butuh sinar matahari penuh — 12 jam atau lebih. Kalau kurang, umbinya tidak akan tumbuh maksimal.',
          '',
          'TIPS',
          'Kalau lahan Anda teduh karena pohon besar, pertimbangkan untuk memangkas cabangnya. Atau pilih tanaman yang tidak butuh banyak sinar matahari, seperti Padi.',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 4: Tentang Filter 1 — Kesesuaian Lingkungan — 5 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_filter1',
    title: 'Tentang Filter 1 — Kesesuaian Lingkungan',
    items: [
      {
        id: 'faq_filter1_apa',
        question: 'Apa itu Tahap 1 (Kesesuaian Lahan)?',
        answer: [
          'Tahap 1 adalah penyaring pertama. Tujuannya sederhana: dari 6 tanaman yang ada, mana yang secara alami bisa hidup di lahan Anda?',
          '',
          'CARA KERJANYA',
          'Sistem mengecek 5 kondisi lahan Anda:',
          '• Keasaman tanah (pH)',
          '• Tekstur tanah',
          '• Ketinggian lahan',
          '• Sinar matahari per hari',
          '• Curah hujan',
          '',
          'Setiap tanaman punya batas minimum dan masing-masing untuk kelima hal di atas. Kalau satu saja tidak cocok, tanaman itu langsung dikeluarkan. Ini bukan penilaian — ini kenyataan alam.',
          '',
          'KENAPA TAHAP 1 PENTING?',
          'Bayangkan kalau sistem langsung menghitung keuntungan tanpa cek kesesuaian lahan. Bisa jadi Bawang Putih (dataran tinggi) direkomendasikan untuk lahan di pantai. Menguntungkan di kertas, mustahil di lapangan.',
          '',
          'Tahap 1 mencegah hal seperti itu. Hasilnya: daftar tanaman yang BISA TUMBUH di lahan Anda. Daftar ini lalu diteruskan ke Tahap 2 untuk dihitung keuntungannya.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_param',
        question: 'Kondisi lahan apa saja yang ditanyakan?',
        answer: [
          'Tahap 1 mengecek 5 kondisi lahan. Ini adalah hal-hal yang paling menentukan apakah suatu tanaman bisa tumbuh dengan baik:',
          '',
          '1. KEASAMAN TANAH (pH)',
          'Seberapa asam atau basa tanah Anda. Contoh: Padi suka agak asam (pH 5,5-6,5), Bawang Putih lebih suka netral (pH 6,0-7,0).',
          '',
          '2. TEKSTUR TANAH',
          'Tanah Anda lebih condong ke liat, lempung, atau berpasir? Contoh: Padi cocok di tanah liat, Bawang Merah lebih suka tanah berpasir.',
          '',
          '3. KETINGGIAN LOKASI',
          'Berapa meter lahan Anda dari permukaan laut. Contoh: Bawang Putih butuh ketinggian 700-1.100 meter. Padi maksimal 650 meter.',
          '',
          '4. SINAR MATAHARI',
          'Berapa jam lahan Anda kena sinar matahari langsung per hari. Contoh: Bawang Merah butuh 12 jam atau lebih. Padi cukup 8-10 jam.',
          '',
          '5. CURAH HUJAN',
          'Seberapa sering dan seberapa banyak hujan di wilayah Anda. Contoh: Padi butuh banyak air. Bawang Merah dan Bawang Putih lebih suka yang agak kering.',
          '',
          'TIDAK PERLU ANGKA PASTI — Sistem akan bertanya dengan bahasa sederhana. Jawab saja sesuai kondisi lahan Anda.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_eliminasi',
        question: 'Mengapa ada tanaman yang dikeluarkan?',
        answer: [
          'Tanaman dikeluarkan karena kondisi lahan Anda tidak cocok dengan kebutuhan alami tanaman itu. Bukan karena jelek — memang tidak cocok.',
          '',
          'CONTOH NYATA',
          '',
          'Lahan Anda di ketinggian 200 meter?',
          '→ Bawang Putih langsung dikeluarkan. Karena Bawang Putih butuh udara pegunungan yang dingin (700-1.100 meter). Di ketinggian 200 meter, Bawang Putih tidak akan menghasilkan umbi yang bagus.',
          '',
          'Tanah Anda sangat asam (pH 4,0)?',
          '→ Kedelai dikeluarkan. Karena Kedelai butuh pH 6,0-7,0. Di tanah terlalu asam, Kedelai tidak bisa serap nutrisi dengan baik.',
          '',
          'Lahan Anda hanya dapat sinar matahari 5 jam per hari?',
          '→ Bawang Merah dikeluarkan. Karena Bawang Merah butuh minimal 12 jam sinar matahari untuk umbinya bisa tumbuh besar.',
          '',
          'TUJUANNYA: Mencegah Anda menanam tanaman yang tidak akan tumbuh meskipun potensi ekonominya terlihat menggiurkan. Lebih baik tahu sebelum tanam daripada menyesal sesudah.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_semua',
        question: 'Bagaimana jika semua tanaman dikeluarkan?',
        answer: [
          'Kalau semua 6 tanaman dikeluarkan, artinya kondisi lahan Anda di luar batas untuk semua tanaman yang ada di sistem. Jangan khawatri — ini jarang terjadi dan bisa diperbaiki.',
          '',
          'PERBAIKAN YANG BISA ANDA LAKUKAN',
          '• Tanah terlalu basah/tergenang → Perbaiki drainase, buat saluran air.',
          '• Tanah terlalu asam → Beri kapur pertanian atau dolomit.',
          '• Tanah terlalu kering → Tambah mulsa atau bahan organik untuk pertahankan kelembaban.',
          '• Curah hujan terlalu rendah → Pertimbangkan sistem irigasi sederhana.',
          '',
          'SETELAH PERBAIKAN',
          '• Coba jalankan sistem lagi dengan data terbaru.',
          '• Kalau masih belum ada yang cocok, konsultasikan dengan penyuluh pertanian atau Dinas Pertanian setempat. Mungkin ada tanaman lain yang lebih cocok untuk kondisi lahan Anda.',
          '',
          'CATATAN: Kondisi ini sangat jarang terjadi. Setidaknya 2-3 dari 6 tanaman biasanya cocok untuk sebagian besar lahan di Indonesia.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_kurangyakin',
        question: 'Apa artinya "kurang yakin"?',
        answer: [
          'Pesan "kurang yakin" artinya sistem belum bisa memastikan kondisi lahan Anda berdasarkan jawaban yang diberikan. Bukan salah Anda — sistem butuh informasi yang lebih jelas.',
          '',
          'KENAPA INI TERJADI',
          '• Jawaban terlalu umum. Misalnya: "tanah saya normal" — normal itu pH berapa?',
          '• Jawaban bisa ditafsirkan lebih dari satu cara. Misalnya: "kadang hadang kadang tidak" — berapa kali seminggu sebenarnya?',
          '',
          'CARA MENGATASINYA',
          '• Jawab dengan lebih spesifik. Tidak perlu angka pasti — deskripsi detail sudah cukup.',
          '• Contoh: alih-alih "normal", coba "tanah saya hitam, agak lengket kalau basah".',
          '• Kalau benar-benar tidak tahu, jawaban terdekat yang Anda pahami sudah membantu.',
          '',
          'Sistem akan bantu klarifikasi jawaban Anda. Tujuannya satu: rekomendasi yang diberikan harus berdasarkan data yang benar.',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 5: Tentang Filter 2 — Analisis Keuntungan — 4 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_filter2',
    title: 'Tentang Filter 2 — Analisis Keuntungan',
    items: [
      {
        id: 'faq_filter2_apa',
        question: 'Apa itu Tahap 2 (Perhitungan Keuntungan)?',
        answer: [
          'Tahap 2 adalah tahap perhitungan keuntungan. Dari tanaman yang sudah lolos Tahap 1 (bisa tumbuh di lahan Anda), mana yang paling menguntungkan?',
          '',
          'CARA KERJANYA',
          'Setiap tanaman yang lolos dihitung berdasarkan 5 faktor ekonomi. Faktor-faktor ini ditimbang sesuai prioritas yang Anda pilih. Hasilnya adalah skor untuk masing-masing tanaman.',
          '',
          'Tanaman dengan skor tertinggi = paling direkomendasikan. Bukan berarti yang lain jelek — hanya saja yang di atas lebih optimal untuk kondisi Anda.',
          '',
          'KENAPA TAHAP 2 PENTING?',
          'Bisa hidup belum tentu menguntungkan. Contoh: Bawang Putih memang bisa tumbuh dan harganya mahal, tapi biaya tanamnya juga paling besar (Rp 91,6 juta/ha). Belum lagi risikonya.',
          '',
          'Tahap 2 membantu Anda melihat gambaran lengkap: bukan cuma "bisa tanam apa", tapi "tanam apa yang paling masuk akal untuk kantong dan kondisi Anda".',
        ].join('\n'),
      },
      {
        id: 'faq_filter2_kriteria',
        question: 'Faktor ekonomi apa saja yang dihitung?',
        answer: [
          'Tahap 2 menghitung 5 faktor ekonomi. Ini gambaran lengkap soal modal, hasil, dan risiko masing-masing tanaman:',
          '',
          'MAKIN RENDAH MAKIN BAIK:',
          '',
          '• Biaya Produksi — Modal tanam per hektar (benih, pupuk, pestisida, tenaga kerja).',
          '• Paling murah: Kedelai (Rp 5,4 juta/ha)',
          '• Paling mahal: Bawang Putih (Rp 91,6 juta/ha)',
          '',
          '• Risiko Gagal Panen — Seberapa rentan terhadap cuaca buruk, hama, dan penyakit.',
          '• Risiko sedang: Padi, Jagung',
          '• Risiko tinggi: Kedelai, Bawang Merah',
          '',
          'MAKIN TINGGI MAKIN BAIK:',
          '',
          '• Harga Jual — Harga pasar rata-rata per kilogram.',
          '• Paling tinggi: Cabai Merah (Rp 52.001/kg)',
          '• Paling rendah: Jagung (Rp 8.438/kg)',
          '',
          '• Hasil Panen — Berapa ton yang bisa dipanen per hektar.',
          '• Paling banyak: Bawang Merah (10,05 ton/ha)',
          '• Paling sedikit: Kedelai (1,62 ton/ha)',
          '',
          '• Permintaan Pasar — Seberapa besar pasar menyerap hasil panen.',
          '• Paling laku: Padi dan Bawang Merah (skor 5)',
          '• Cukup laku: Jagung dan Kedelai (skor 4)',
        ].join('\n'),
      },
      {
        id: 'faq_filter2_pref',
        question: 'Bagaimana cara memilih prioritas?',
        answer: [
          'Di Tahap 2, Anda diminta memilih prioritas — hal yang paling penting untuk Anda. Ini mempengaruhi perhitungan ranking.',
          '',
          'CONTOH PILIHAN PRIORITAS',
          '',
          '• "Modal terbatas"',
          '  → Biaya tanam akan diutamakan. Tanaman dengan biaya rendah akan naik peringkat.',
          '',
          '• "Takut rugi"',
          '  → Risiko gagal panen akan diutamakan. Tanaman yang lebih aman akan naik peringkat.',
          '',
          '• "Cepat laku"',
          '  → Permintaan pasar akan diutamakan. Tanaman yang paling laku di pasaran akan naik peringkat.',
          '',
          'TIPS',
          'Pilih prioritas yang benar-benar sesuai kondisi Anda. Jangan pilih semua faktor sebagai prioritas — nanti hasilnya tidak akan berbeda satu sama lain.',
        ].join('\n'),
      },
      {
        id: 'faq_filter2_hasil',
        question: 'Bagaimana cara membaca hasil ranking?',
        answer: [
          'Setelah perhitungan selesai, sistem menampilkan daftar tanaman dari yang paling direkomendasikan sampai ke yang paling bawah.',
          '',
          'CARA MEMBACA HASIL',
          '',
          '• PERINGKAT 1 = tanaman paling optimal untuk lahan Anda.',
          '  Skornya paling tinggi karena paling cocok DAN paling menguntungkan.',
          '',
          '• SKOR (dari 100) = seberapa optimal tanaman itu untuk Anda.',
          '  Makin tinggi makin bagus. Tidak ada batas "lulus" atau "tidak lulus" — ini perbandingan.',
          '',
          '• DATA EKONOMI = biaya, harga jual, hasil panen, risiko, dan permintaan.',
          '  Ini untuk Anda bandingkan sendiri antar tanaman.',
          '',
          'CONTOH',
          'Padi di peringkat 1 dengan skor 78 → Padi paling cocok untuk lahan Anda. Biaya rendah, risiko sedang, dan permintaan sangat tinggi.',
          '',
          'Bawang Merah di peringkat 2 dengan skor 65 → Juga cocok, tapi biaya tanamnya yang tinggi membuat skornya di bawah Padi.',
          '',
          'CATATAN',
          '• Ranking hanya untuk tanaman yang lolos Tahap 1.',
          '• Kalau cuma 1 tanaman yang lolos, sistem tetap tampilkan data ekonominya sebagai referensi.',
        ].join('\n'),
      },
    ],
  },
];
