/**
 * FAQ Content — Agri-SAW Pro Chatbot
 * Source: SPK.md, dasar knowledge base.md
 * 5 Kategori, 19 Pertanyaan
 */

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
}

export interface FaqSection {
  id: string;
  title: string;
  items: FaqItem[];
}

export const FAQ_CONTENT: FaqSection[] = [
  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 1: Tentang Sistem — 4 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_sistem',
    title: 'Tentang Sistem',
    items: [
      {
        id: 'faq_sistem_apa',
        question: 'Apa itu Agri-SAW Pro?',
        answer: [
          'Agri-SAW Pro adalah **Sistem Pendukung Keputusan (SPK)** yang dirancang untuk membantu petani Indonesia memilih komoditas pertanian terbaik berdasarkan **kondisi lingkungan lahan** dan **analisis keuntungan ekonomi**.',
          '',
          'Sistem ini menggunakan metode **Simple Additive Weighting (SAW)** dengan pendekatan **Double Filter**:',
          '',
          '• **Filter 1 — Kesesuaian Lingkungan**: Menyaring komoditas yang secara biologis cocok dengan lahan Anda (pH tanah, tekstur tanah, ketinggian, intensitas cahaya, curah hujan).',
          '• **Filter 2 — Analisis Keuntungan**: Meranking komoditas yang lolos berdasarkan data ekonomi (biaya produksi, harga jual, produktivitas, risiko gagal panen, permintaan pasar).',
          '',
          'Hasil akhirnya adalah rekomendasi komoditas yang tidak hanya **cocok dengan lahan** Anda, tetapi juga **menguntungkan secara finansial** — sehingga Anda terhindar dari risiko gagal panen dan kerugian ekonomi.',
          '',
          'Sistem ini dikembangkan oleh mahasiswa Program Studi Informatika UIN Sunan Kalijaga Yogyakarta sebagai bagian dari penelitian Sistem Pendukung Keputusan.',
        ].join('\n'),
      },
      {
        id: 'faq_sistem_komoditas',
        question: 'Apa saja komoditas yang didukung?',
        answer: [
          'Saat ini Agri-SAW Pro mendukung **6 komoditas utama** yang paling banyak dibudidayakan di Indonesia:',
          '',
          '• 🌾 **Padi** — Tanaman pangan pokok, pH 5,5–6,5, ketinggian 0–650 mdpl, curah hujan 1.500–2.000 mm/tahun',
          '• 🌽 **Jagung** — Tanaman pangan serbaguna, pH 5,6–7,5, ketinggian 0–900 mdpl, curah hujan 500–1.200 mm/musim',
          '• 🫘 **Kedelai** — Tanaman legum perbaik tanah, pH 6,0–7,0, ketinggian 0–900 mdpl, curah hujan 350–600 mm/musim',
          '• 🌶️ **Cabai Merah** — Hortikultura bernilai tinggi, pH 6,0–7,0, ketinggian 0–1.400 mdpl, curah hujan 600–1.250 mm/tahun',
          '• 🧅 **Bawang Merah** — Sayuran permintaan tinggi, pH 5,6–6,5, ketinggian 0–800 mdpl, curah hujan 300–400 mm/musim',
          '• 🧄 **Bawang Putih** — Sayuran dataran tinggi, pH 6,0–7,0, ketinggian 700–1.100 mdpl, curah hujan 110–200 mm/bulan',
          '',
          'Keenam komoditas ini dipilih karena memiliki **nilai ekonomi signifikan**, **permintaan pasar tinggi**, dan **karakteristik agroklimat yang berbeda-beda** — sehingga sistem bisa memberikan perbandingan yang komprehensif.',
        ].join('\n'),
      },
      {
        id: 'faq_sistem_cara',
        question: 'Bagaimana cara kerja sistem?',
        answer: [
          'Agri-SAW Pro bekerja dalam **2 tahap analisis berurutan**:',
          '',
          '**Tahap 1 — Filter Kesesuaian Lingkungan (Rule-Based)**',
          'Anda akan diminta menjawab pertanyaan tentang kondisi lahan Anda: pH tanah, tekstur tanah, ketinggian lokasi, intensitas cahaya matahari, dan curah hujan. Jawaban Anda bisa dalam bahasa sehari-hari — tidak perlu angka teknis. Sistem kemudian mencocokkan data Anda dengan database agroklimat setiap komoditas. Jika **satu saja** parameter di luar rentang optimal, komoditas tersebut **langsung dieliminasikan**.',
          '',
          '**Tahap 2 — Filter Analisis Keuntungan (SAW)**',
          'Komoditas yang lolos Tahap 1 kemudian dihitung nilai preferensinya menggunakan metode SAW berdasarkan 5 kriteria ekonomi: biaya produksi, harga jual, produktivitas, risiko gagal panen, dan permintaan pasar. Anda bisa memilih **prioritas** untuk menentukan bobot kriteria yang lebih penting bagi Anda.',
          '',
          '**Hasil Akhir**',
          'Sistem menampilkan **ranking komoditas** yang paling optimal dan menguntungkan untuk lahan Anda, lengkap dengan penjelasan mengapa komoditas tersebut direkomendasikan.',
        ].join('\n'),
      },
      {
        id: 'faq_sistem_filter',
        question: 'Apa perbedaan Filter 1 dan Filter 2?',
        answer: [
          'Kedua filter ini memiliki **fungsi dan mekanisme yang berbeda**, namun saling melengkapi:',
          '',
          '**Filter 1 — Kesesuaian Lingkungan**',
          '• **Fungsi**: Menentukan apakah suatu komoditas **secara biologis bisa tumbuh** di lahan Anda',
          '• **Mekanisme**: Validasi Boolean (Rule-Based) — setiap parameter lahan dicek terhadap rentang optimal komoditas',
          '• **Sifat**: **Hard Constraint** — jika satu parameter di luar batas, komoditas langsung dieliminasikan tanpa toleransi',
          '• **Parameter**: pH tanah, tekstur tanah, ketinggian, intensitas cahaya, curah hujan',
          '',
          '**Filter 2 — Analisis Keuntungan**',
          '• **Fungsi**: Menentukan komoditas mana yang **paling menguntungkan secara ekonomi** dari yang lolos Filter 1',
          '• **Mekanisme**: Perhitungan SAW (Simple Additive Weighting) dengan normalisasi matriks dan pembobotan kriteria',
          '• **Sifat**: **Soft Constraint** — semua kriteria ekonomi ditimbang bersama untuk menghasilkan ranking',
          '• **Parameter**: Biaya produksi, harga jual, produktivitas, risiko gagal panen, permintaan pasar',
          '',
          '**Analogi sederhana**: Filter 1 memastikan tanaman **bisa hidup**, Filter 2 memastikan tanaman **menguntungkan**.',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 2: Tentang Komoditas — 3 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_komoditas',
    title: 'Tentang Komoditas',
    items: [
      {
        id: 'faq_komoditas_daftar',
        question: 'Apa saja komoditas yang didukung?',
        answer: [
          'Agri-SAW Pro saat ini mendukung **6 komoditas** yang merupakan tanaman pangan dan hortikultura utama di Indonesia:',
          '',
          '• 🌾 **Padi** — Komoditas pangan pokok dengan permintaan pasar tertinggi (rating 5). Biaya produksi Rp7,2 juta/ha, produktivitas 5,28 ton/ha.',
          '• 🌽 **Jagung** — Tanaman pangan serbaguna dengan biaya produksi terendah kedua (Rp6,2 juta/ha) dan produktivitas 5,57 ton/ha.',
          '• 🫘 **Kedelai** — Tanaman legum yang bisa mengikat nitrogen secara alami, biaya produksi terendah (Rp5,4 juta/ha), harga jual tinggi (Rp16.459/kg).',
          '• 🌶️ **Cabai Merah** — Hortikultura dengan harga jual tertinggi (Rp52.001/kg), namun biaya produksi juga tinggi (Rp48,5 juta/ha).',
          '• 🧅 **Bawang Merah** — Sayuran dengan produktivitas tertinggi (10,05 ton/ha) dan permintaan pasar sangat tinggi (rating 5).',
          '• 🧄 **Bawang Putih** — Sayuran dataran tinggi dengan biaya produksi tertinggi (Rp91,6 juta/ha), namun harga jual dan permintaan juga tinggi.',
          '',
          'Masing-masing komoditas memiliki **persyaratan agroklimat yang berbeda**, sehingga tidak semua komoditas cocok untuk setiap lahan.',
        ].join('\n'),
      },
      {
        id: 'faq_komoditas_mengapa',
        question: 'Mengapa hanya 6 komoditas?',
        answer: [
          'Pemilihan 6 komoditas ini didasarkan pada **pertimbangan penelitian** yang telah ditetapkan dalam batasan masalah:',
          '',
          '• **Representativitas pangan**: Padi, jagung, dan kedelai adalah tanaman pangan utama penyumbang ketahanan pangan nasional.',
          '• **Nilai ekonomi tinggi**: Cabai merah, bawang merah, dan bawang putih adalah komoditas hortikultura dengan harga jual dan permintaan pasar yang signifikan.',
          '• **Keragaman agroklimat**: Keenam komoditas ini memiliki karakteristik kebutuhan lingkungan yang **berbeda-beda** — dari dataran rendah hingga dataran tinggi, dari tanah lembab hingga tanah kering — sehingga sistem bisa memberikan perbandingan yang bermakna.',
          '• **Ketersediaan data**: Data agroklimat dan ekonomi untuk 6 komoditas ini tersedia dari sumber resmi (BPS, Kementerian Pertanian) yang memadai untuk perhitungan SAW.',
          '',
          'Penelitian ini difokuskan pada **kedalaman analisis** daripada **jumlah komoditas**, agar rekomendasi yang dihasilkan benar-benar akurat dan dapat dipertanggungjawabkan secara ilmiah.',
        ].join('\n'),
      },
      {
        id: 'faq_komoditas_tidakada',
        question: 'Bagaimana jika komoditas saya tidak ada?',
        answer: [
          'Jika komoditas yang Anda inginkan tidak termasuk dalam 6 komoditas yang didukung, berikut beberapa hal yang perlu Anda ketahui:',
          '',
          '• **Sistem hanya bisa menganalisis komoditas yang ada dalam database**. Ini karena setiap komoditas memiliki parameter agroklimat dan data ekonomi spesifik yang sudah diteliti dan diverifikasi.',
          '',
          '• **Anda tetap bisa menggunakan sistem** untuk melihat dari 6 komoditas yang ada, mana yang paling cocok dengan lahan Anda. Misalnya, jika Anda ingin menanam kentang, Anda bisa melihat bahwa karakteristik kentang mirip dengan beberapa komoditas yang didukung.',
          '',
          '• **Alternatif lain**: Anda bisa berkonsultasi dengan **penyuluh pertanian setempat** atau **Dinas Pertanian kabupaten/kota** untuk mendapatkan rekomendasi komoditas yang tidak tercakup dalam sistem.',
          '',
          '• **Ke depan**: Pengembangan sistem selanjutnya dapat menambahkan lebih banyak komoditas dengan memperluas database agroklimat dan data ekonomi.',
          '',
          'Jangan khawatir — meskipun komoditas Anda tidak ada di daftar, sistem tetap bisa membantu Anda memilih **komoditas terbaik dari yang tersedia** untuk kondisi lahan Anda.',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 3: Tentang Kondisi Lingkungan — 4 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_lingkungan',
    title: 'Tentang Kondisi Lingkungan',
    items: [
      {
        id: 'faq_lingkungan_ph',
        question: 'Bagaimana mengukur pH tanah?',
        answer: [
          '**pH tanah** mengukur tingkat keasaman atau kebasaan tanah pada skala 0–14. pH 7 bersifat netral, di bawah 7 bersifat asam, dan di atas 7 bersifat basa (alkalis).',
          '',
          '**Cara sederhana untuk memperkirakan pH tanah**:',
          '• **Tanaman sering menguning dan kerdil** meskipun sudah dipupuk → kemungkinan tanah **masam** (pH di bawah 5,5)',
          '• **Tanaman tumbuh hijau subur** → kemungkinan tanah **netral** (pH 6,0–7,0)',
          '',
          '**Cara mengukur pH tanah secara lebih akurat**:',
          '• Gunakan **kertas lakmus** atau **pH meter digital** yang tersedia di toko pertanian',
          '• Ambil sampel tanah dari kedalaman 15–20 cm, keringkan, lalu larutkan dalam air dengan perbandingan 1:2,5',
          '• Ukur larutan tersebut dengan alat ukur pH',
          '',
          '**Rentang pH optimal untuk komoditas yang didukung**:',
          '• Padi: 5,5–6,5 | Jagung: 5,6–7,5 | Kedelai: 6,0–7,0',
          '• Cabai Merah: 6,0–7,0 | Bawang Merah: 5,6–6,5 | Bawang Putih: 6,0–7,0',
          '',
          '**Tips**: Jika tanah terlalu asam, Anda bisa melakukan **pengapuran** menggunakan dolomit atau kapur pertanian. Jika terlalu basa, tambahkan **bahan organik** seperti kompos atau pupuk kandang.',
        ].join('\n'),
      },
      {
        id: 'faq_lingkungan_tekstur',
        question: 'Bagaimana mengetahui tekstur tanah?',
        answer: [
          '**Tekstur tanah** merujuk pada komposisi partikel pasir, debu, dan lempung dalam tanah. Tekstur tanah menentukan kemampuan tanah menahan air dan nutrisi.',
          '',
          '**Cara sederhana untuk mengetahui tekstur tanah**:',
          '• Ambil segenggam tanah basah, lalu remas:',
          '  - **Terasa sangat lengket dan sulit lepas dari tangan** → Tanah **Liat** (cocok untuk Padi)',
          '  - **Terasa kasar seperti pasir, mudah hancur** → Tanah **Lempung Berpasir** (cocok untuk Cabai, Bawang Merah/Putih)',
          '  - **Terasa sedikit lengket, bisa dibentuk** → Tanah **Lempung Berliat** (cocok untuk Jagung, Kedelai)',
          '',
          '**Karakteristik masing-masing tekstur**:',
          '• **Liat**: Menahan air dengan baik, subur tapi sulit diolah saat kering. Ideal untuk Padi yang butuh genangan.',
          '• **Lempung Berpasir**: Drainase baik, cepat panas, mudah diolah. Cocok untuk tanaman yang tidak tergenang.',
          '• **Lempung Berliat**: Keseimbangan antara drainase dan retensi air. Paling serbaguna untuk berbagai tanaman.',
          '',
          '**Hubungan dengan komoditas**:',
          '• Padi → Liat / Liat berlempung',
          '• Jagung → Lempung berpasir – berliat',
          '• Kedelai → Lempung berliat',
          '• Cabai Merah → Lempung berpasir',
          '• Bawang Merah → Lempung berpasir',
          '• Bawang Putih → Lempung berpasir',
        ].join('\n'),
      },
      {
        id: 'faq_lingkungan_hujan',
        question: 'Bagaimana menghitung curah hujan?',
        answer: [
          '**Curah hujan** adalah jumlah air hujan yang jatuh pada suatu area dalam periode tertentu, biasanya dinyatakan dalam milimeter (mm) per tahun, per musim, atau per bulan.',
          '',
          '**Cara sederhana memperkirakan curah hujan**:',
          '• **Hampir tiap hari hujan** dalam satu musim → Curah hujan **Tinggi** (800–1.500 mm/tahun)',
          '• **Sering hujan** (beberapa kali seminggu) → Curah hujan **Sedang** (400–800 mm/musim)',
          '• **Hanya sesekali hujan** → Curah hujan **Rendah** (200–400 mm/musim)',
          '',
          '**Cara mengukur curah hujan secara akurat**:',
          '• Gunakan **penakar hujan (rain gauge)** — wadah silinder yang diletakkan di area terbuka',
          '• Ukur tinggi air yang terkumpul setelah hujan dalam milimeter',
          '• Lakukan pengukuran setiap hari selama minimal 1 bulan untuk mendapatkan rata-rata',
          '',
          '**Rentang curah hujan optimal untuk komoditas**:',
          '• Padi: 1.500–2.000 mm/tahun (butuh banyak air)',
          '• Jagung: 500–1.200 mm/musim',
          '• Kedelai: 350–600 mm/musim',
          '• Cabai Merah: 600–1.250 mm/tahun',
          '• Bawang Merah: 300–400 mm/musim',
          '• Bawang Putih: 110–200 mm/bulan',
          '',
          '**Catatan penting**: Sistem Agri-SAW Pro akan **menormalisasi** satuan curah hujan Anda (baik per tahun, musim, atau bulan) ke metrik yang sama untuk memastikan perbandingan yang konsisten.',
        ].join('\n'),
      },
      {
        id: 'faq_lingkungan_cahaya',
        question: 'Bagaimana mengukur intensitas cahaya?',
        answer: [
          '**Intensitas cahaya** dalam konteks pertanian mengacu pada **lama paparan sinar matahari langsung** yang diterima lahan setiap hari, diukur dalam jam per hari.',
          '',
          '**Cara sederhana memperkirakan intensitas cahaya**:',
          '• Hitung berapa jam lahan Anda terpapar sinar matahari **tanpa terhalang** pohon besar, bangunan, atau atap',
          '• **8–10 jam** → cocok untuk Padi dan Jagung',
          '• **10–12 jam** → cocok untuk Kedelai dan Cabai Merah',
          '• **12+ jam** → cocok untuk Bawang Merah dan Bawang Putih',
          '',
          '**Skala intensitas cahaya dalam sistem**:',
          '• **Rating 1**: Kurang dari 6 jam (sangat rendah)',
          '• **Rating 2**: 6–8 jam (rendah)',
          '• **Rating 3**: 8–10 jam (sedang — cocok untuk Padi, Jagung)',
          '• **Rating 4**: 10–12 jam (tinggi — cocok untuk Kedelai, Cabai Merah)',
          '• **Rating 5**: 12+ jam (sangat tinggi — cocok untuk Bawang Merah, Bawang Putih)',
          '',
          '**Tips**:',
          '• Lahan yang teduh karena pohon besar atau bangunan akan mengurangi intensitas cahaya',
          '• Tanaman seperti Bawang Putih dan Bawang Merah **sangat membutuhkan** sinar matahari penuh (12+ jam) untuk menghasilkan umbi yang baik',
          '• Jika lahan Anda teduh, pertimbangkan untuk memangkas pohon peneduh atau memilih komoditas yang toleran terhadap naungan',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 4: Tentang Filter 1 — Kesesuaian Lingkungan — 5 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_filter1',
    title: 'Tentang Filter 1 — Kesesuaian Lingkungan',
    items: [
      {
        id: 'faq_filter1_apa',
        question: 'Apa itu Filter 1?',
        answer: [
          '**Filter 1** adalah tahap pertama dalam sistem Agri-SAW Pro yang berfungsi sebagai **gerbang eliminasi mutlak** (*Hard Constraint*) untuk menentukan apakah suatu komoditas **secara biologis mampu tumbuh** di lahan Anda.',
          '',
          '**Cara kerja Filter 1**:',
          '• Sistem menerima input kondisi lahan Anda: pH tanah, tekstur tanah, ketinggian, intensitas cahaya, dan curah hujan',
          '• Setiap parameter dicek terhadap **rentang optimal** yang sudah ditetapkan dalam database agronomis untuk masing-masing komoditas',
          '• Jika **satu saja** parameter berada di luar rentang yang diizinkan, komoditas tersebut **langsung dieliminasikan** — terlepas dari potensi keuntungan ekonominya',
          '',
          '**Mengapa Filter 1 penting?**',
          'Tanpa filter ini, sistem bisa saja merekomendasikan komoditas dengan margin profit tinggi (seperti Bawang Merah atau Bawang Putih) pada lahan yang secara biofisik **tidak mendukung** pertumbuhannya. Filter 1 mencegah "Halusinasi Ekonomi" — rekomendasi yang menguntungkan di kertas tapi mustahil di lapangan.',
          '',
          '**Output Filter 1**: Daftar pendek (*shortlist*) komoditas yang secara agronomis "Layak Tanam", yang kemudian diteruskan ke Filter 2 untuk analisis keuntungan.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_param',
        question: 'Parameter apa saja yang ditanyakan?',
        answer: [
          'Filter 1 memeriksa **5 parameter agroklimat** yang menentukan kesesuaian komoditas dengan lahan Anda:',
          '',
          '• **pH Tanah** — Tingkat keasaman tanah (skala 0–14). Contoh: Padi butuh pH 5,5–6,5, Bawang Putih butuh pH 6,0–7,0.',
          '',
          '• **Tekstur Tanah** — Komposisi partikel tanah: liat, lempung berpasir, atau lempung berliat. Contoh: Padi cocok di tanah liat, Bawang Merah di lempung berpasir.',
          '',
          '• **Ketinggian Lokasi (mdpl)** — Ketinggian lahan di atas permukaan laut. Contoh: Bawang Putih butuh ketinggian 700–1.100 mdpl, Padi maksimal 650 mdpl.',
          '',
          '• **Intensitas Cahaya (jam/hari)** — Lama paparan sinar matahari langsung. Contoh: Bawang Merah butuh 12+ jam, Padi cukup 8–10 jam.',
          '',
          '• **Curah Hujan** — Jumlah air hujan di wilayah Anda. Contoh: Padi butuh 1.500–2.000 mm/tahun, Kedelai cukup 350–600 mm/musim.',
          '',
          '**Yang perlu diingat**: Anda **tidak perlu** memberikan angka pasti. Chatbot akan bertanya dalam bahasa sehari-hari (misalnya: "Apakah lahan Anda di dataran rendah atau pegunungan?") dan sistem akan mengkonversi jawaban Anda ke nilai numerik.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_eliminasi',
        question: 'Mengapa tanaman dieliminasi?',
        answer: [
          'Tanaman dieliminasi dari daftar kandidat ketika **kondisi lahan tidak memenuhi syarat minimum** untuk pertumbuhan optimal tanaman tersebut.',
          '',
          '**Logika eliminasi**:',
          '• Sistem menggunakan validasi **Boolean** — setiap parameter lahan dicek apakah berada dalam rentang [Min, Max] yang diizinkan',
          '• `IF (Input_User < Min_Optimal) OR (Input_User > Max_Optimal) THEN Komoditas = Dieliminasikan`',
          '• **Tidak ada toleransi** — meskipun hanya sedikit di luar batas, komoditas tetap dieliminasikan',
          '',
          '**Contoh konkret**:',
          '• Jika lahan Anda di ketinggian **200 mdpl**, maka **Bawang Putih** (butuh 700–1.100 mdpl) langsung dieliminasikan karena butuh udara pegunungan yang dingin',
          '• Jika tanah Anda sangat masam (pH **4,0**), maka **Kedelai** (butuh pH 6,0–7,0) dieliminasikan karena tidak bisa tumbuh optimal di tanah terlalu asam',
          '• Jika lahan Anda mendapat sinar matahari hanya **5 jam/hari**, maka **Bawang Merah** (butuh 12+ jam) dieliminasikan',
          '',
          '**Tujuan eliminasi**: Mencegah Anda menanam komoditas yang secara biologis **tidak akan tumbuh meskipun** potensi ekonominya menjanjikan.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_semua',
        question: 'Bagaimana jika semua tanaman dieliminasi?',
        answer: [
          'Jika **semua 6 komoditas** dieliminasikan, artinya kondisi lahan Anda berada di luar rentang optimal untuk semua komoditas yang didukung sistem.',
          '',
          '**Yang akan terjadi**:',
          '• Sistem akan menampilkan pesan bahwa tidak ada komoditas yang cocok berdasarkan kondisi yang Anda berikan',
          '• Sistem akan memberikan **saran perbaikan** yang bisa Anda lakukan, misalnya:',
          '  - Perbaiki **drainase** jika tanah terlalu basah/tergenang',
          '  - Lakukan **pengapuran** (dolomit/kapur) jika tanah terlalu asam',
          '  - Tambah **mulsa** atau bahan organik jika tanah terlalu kering',
          '  - Pertimbangkan **sistem irigasi** jika curah hujan rendah',
          '',
          '**Langkah selanjutnya**:',
          '• Anda bisa **mencoba kembali** dengan kondisi yang lebih spesifik atau setelah melakukan perbaikan lahan',
          '• Konsultasikan dengan **penyuluh pertanian** atau **Dinas Pertanian setempat** untuk rekomendasi komoditas di luar 6 komoditas yang didukung',
          '',
          '**Catatan**: Kondisi ini jarang terjadi dalam praktik nyata, karena setidaknya beberapa dari 6 komoditas biasanya cocok untuk sebagian besar lahan di Indonesia.',
        ].join('\n'),
      },
      {
        id: 'faq_filter1_kurangyakin',
        question: 'Apa artinya "kurang yakin"?',
        answer: [
          'Pesan "kurang yakin" muncul ketika sistem **tidak bisa menentukan** kondisi lahan Anda secara pasti berdasarkan jawaban yang diberikan.',
          '',
          '**Penyebab munculnya pesan ini**:',
          '• Jawaban Anda **tidak cukup spesifik** untuk dikonversi ke parameter yang dibutuhkan sistem',
          '• Jawaban Anda **ambigu** atau bisa diinterpretasikan ke beberapa kategori sekaligus',
          '• Data yang Anda berikan **tidak konsisten** dengan parameter lain',
          '',
          '**Contoh situasi**:',
          '• Jika Anda menjawab "tanah saya normal" untuk pertanyaan pH — sistem tidak tahu apakah yang Anda maksud pH 6,0 atau pH 7,0, karena keduanya bisa dianggap "normal"',
          '• Jika Anda menjawab "kadang hujan kadang tidak" untuk curah hujan — sistem perlu informasi lebih spesifik tentang frekuensi dan intensitas',
          '',
          '**Cara mengatasinya**:',
          '• Berikan jawaban yang **lebih detail** dan **spesifik**',
          '• Jika Anda tidak tahu angka pastinya, deskripsikan kondisi Anda sedetail mungkin (misalnya: "tanah saya sering tergenang saat hujan" atau "tanah saya sangat kering di musim kemarau")',
          '• Sistem akan membantu **mengklarifikasi** jawaban Anda dengan pertanyaan lanjutan',
          '',
          '**Tujuan**: Memastikan rekomendasi yang diberikan sistem **seakurat mungkin** berdasarkan data yang valid.',
        ].join('\n'),
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────────
  // Kategori 5: Tentang Filter 2 — Analisis Keuntungan — 4 pertanyaan
  // ──────────────────────────────────────────────────────────────────────────────
  {
    id: 'cat_filter2',
    title: 'Tentang Filter 2 — Analisis Keuntungan',
    items: [
      {
        id: 'faq_filter2_apa',
        question: 'Apa itu Filter 2?',
        answer: [
          '**Filter 2** adalah tahap kedua dalam sistem Agri-SAW Pro yang berfungsi untuk **meranking komoditas** yang telah lolos Filter 1 berdasarkan **keuntungan ekonomi** menggunakan metode **Simple Additive Weighting (SAW)**.',
          '',
          '**Cara kerja Filter 2**:',
          '• Komoditas yang lolos Filter 1 (secara biologis cocok) dievaluasi berdasarkan **5 kriteria ekonomi**',
          '• Setiap kriteria dinormalisasi ke skala 0–1 agar bisa diperbandingkan',
          '• Hasil normalisasi dikalikan dengan **bobot** masing-masing kriteria dan dijumlahkan untuk mendapatkan **nilai preferensi (Vᵢ)**',
          '• Komoditas dengan nilai Vᵢ **paling mendekati 1** adalah yang paling optimal',
          '',
          '**Mengapa Filter 2 diperlukan?**',
          'Karena tidak ada gunanya menanam komoditas yang cocok dengan lahan tapi **tidak menguntungkan secara ekonomi**. Filter 2 memastikan rekomendasi akhir adalah komoditas yang **secara agronomis cocok DAN secara finansial menguntungkan**.',
          '',
          '**Contoh**: Bawang Merah dan Bawang Putih sama-sama lolos Filter 1 untuk lahan tertentu. Tapi Filter 2 akan menghitung mana yang lebih menguntungkan berdasarkan biaya, harga, produktivitas, risiko, dan permintaan — dan menghasilkan ranking yang objektif.',
        ].join('\n'),
      },
      {
        id: 'faq_filter2_kriteria',
        question: 'Kriteria ekonomi apa saja yang dihitung?',
        answer: [
          'Filter 2 menggunakan **5 kriteria ekonomi** yang merepresentasikan dinamika modal, hasil, dan risiko pasar:',
          '',
          '**Kriteria Cost (semakin kecil, semakin baik)**:',
          '• **Biaya Produksi (Rp/ha)** — Total modal yang dikeluarkan per hektar (benih, pupuk, pestisida, tenaga kerja). Bobot: 20%.',
          '  - Contoh: Kedelai paling rendah (Rp5,37 juta/ha), Bawang Putih paling tinggi (Rp91,6 juta/ha)',
          '• **Risiko Gagal Panen (Skala 1–3)** — Tingkat kerentanan terhadap cuaca, hama, dan penyakit. Bobot: 10%.',
          '  - Padi dan Jagung: risiko sedang (2), Kedelai dan Bawang Merah: risiko tinggi (3)',
          '',
          '**Kriteria Benefit (semakin besar, semakin baik)**:',
          '• **Harga Jual (Rp/kg)** — Rata-rata harga pasar nasional. Bobot: 25%.',
          '  - Cabai Merah tertinggi (Rp52.001/kg), Jagung terendah (Rp8.438/kg)',
          '• **Produktivitas (ton/ha)** — Volume output per hektar. Bobot: 25%.',
          '  - Bawang Merah tertinggi (10,05 ton/ha), Kedelai terendah (1,62 ton/ha)',
          '• **Permintaan Pasar (Skala 1–5)** — Kapasitas serap pasar. Bobot: 10%.',
          '  - Padi dan Bawang Merah tertinggi (5), Jagung dan Kedelai (4)',
          '',
          'Total bobot: **100%**. Biaya Produksi dan Harga Jual mendapat bobot tertinggi karena merupakan penentu fundamental kelayakan finansial.',
        ].join('\n'),
      },
      {
        id: 'faq_filter2_pref',
        question: 'Bagaimana cara memilih preferensi?',
        answer: [
          'Di Filter 2, Anda bisa memilih **prioritas ekonomi** yang paling penting bagi Anda. Preferensi ini akan menentukan **bobot** masing-masing kriteria dalam perhitungan SAW.',
          '',
          '**Cara kerja preferensi**:',
          '• Anda memilih **kata kunci** yang mencerminkan prioritas Anda, misalnya:',
          '  - "Modal mepet" atau "Cari yang murah" → bobot **Biaya Produksi** meningkat',
          '  - "Takut rugi" atau "Banyak hama" → bobot **Risiko Gagal Panen** meningkat',
          '  - "Cepat laku" atau "Pasar luas" → bobot **Permintaan Pasar** meningkat',
          '',
          '**Formula normalisasi bobot dinamis**:',
          '• Sistem menetapkan **Rating Kepentingan (R)** untuk setiap kriteria berdasarkan prioritas Anda (skala 1–5)',
          '• Bobot dihitung dengan rumus: **Wⱼ = Rⱼ / ΣRᵢ** (total semua bobot = 100%)',
          '',
          '**Contoh**:',
          '• Jika Anda sangat peduli pada keuntungan (Harga Jual = 5) dan risiko (Risiko = 5), sementara kriteria lain standar (3), maka total R = 22',
          '• Bobot Harga Jual = 5/22 = **22,7%**, Bobot Risiko = 5/22 = **22,7%**',
          '',
          '**Tips**: Pilih preferensi yang **benar-benar sesuai** dengan kondisi nyata Anda. Jangan memilih semua kriteria sebagai prioritas tertinggi karena akan mengurangi diferensiasi hasil.',
        ].join('\n'),
      },
      {
        id: 'faq_filter2_hasil',
        question: 'Bagaimana membaca hasil ranking?',
        answer: [
          'Setelah perhitungan SAW selesai, sistem akan menampilkan **ranking komoditas** dari yang paling optimal hingga yang paling rendah.',
          '',
          '**Cara membaca hasil**:',
          '• **Peringkat 1** adalah komoditas yang paling direkomendasikan — memiliki keseimbangan terbaik antara kesesuaian lingkungan dan keuntungan ekonomi',
          '• **Nilai preferensi (Vᵢ)** menunjukkan skor komoditas (0–1). Semakin mendekati 1, semakin optimal',
          '• Sistem juga menampilkan **data ekonomi** setiap komoditas: biaya produksi, harga jual, produktivitas, risiko, dan permintaan',
          '',
          '**Contoh interpretasi**:',
          '• Jika **Padi** di peringkat 1 dengan Vᵢ = 0,85, artinya Padi adalah komoditas paling optimal untuk lahan Anda — biaya rendah (Rp7,2 juta/ha), risiko sedang, dan permintaan sangat tinggi',
          '• Jika **Bawang Merah** di peringkat 2 dengan Vᵢ = 0,72, artinya Bawang Merah juga cocok tapi beban biaya produksinya yang tinggi (Rp58,5 juta/ha) mengurangi skor akhirnya',
          '',
          '**Hal yang perlu diperhatikan**:',
          '• Ranking hanya berlaku untuk komoditas yang **lolos Filter 1** — komoditas yang dieliminasikan tidak muncul di daftar',
          '• Jika hanya 1 komoditas yang lolos, sistem tetap menampilkan data ekonominya sebagai referensi',
          '• Hasil akhir disajikan dalam **bahasa persuasif** yang membandingkan keunggulan ekonomi antar komoditas',
        ].join('\n'),
      },
    ],
  },
];
